### ISSUE TITLE
Invalid function: omni-kill-generate-copy-command

### ISSUE THREAD

**Issue by jack99999** [AdrieanKhisbe/omni-kill.el#2] opened 2015-05-26 06:41 UTC
hi

just installed from elpa.

when i load, i get this:

Loading omni-kill...
omni-kill-generate-all-the-fun: Invalid function: omni-kill-generate-copy-command

cheers

jack

**Comment by AdrieanKhisbe** [comment] 2015-05-26 07:11
Hey @jack99999, I can't reproduce on my emacs/prelude setup.

Are you using elpa-stable, or not?
(I so I just need to release a patch version)

**Comment by jack99999** [comment] 2015-05-26 07:17
hi

i'm using http://melpa.milkbox.net/packages/

...and i confess that i don't actually know whether that is stable or otherwise...

and emacs tells me:

omni-kill is an installed package.

```
 Status: Installed in `~/.emacs.d/elpa/omni-kill-20150525.937/' (unsigned).
Archive: n/a
Version: 20150525.937
Summary: Kill all the things
```

   Keywords: convenience editing tools 
    Other versions: 20150525.937 (melpa).

jack

**Comment by AdrieanKhisbe** [comment] 2015-05-26 07:18
Okey then It's non stable, so you really have the latest.

What did you get when running:

```
 emacs --version
```

**Comment by jack99999** [comment] 2015-05-26 07:20
GNU Emacs 24.4.1 (x86_64-w64-mingw32) of 2014-10-21 on KAEL

**Comment by AdrieanKhisbe** [comment] 2015-05-26 07:22
Strange, I just test this specific version it on a fresh emacs, could not reproduce

```
 emacs --version
 GNU Emacs 24.4.1
```

Could you try `emacs  --debug-init -Q -l omni-kill-20150525.937.el.txt` and tell me what happen?
(adapt the path to the file)

**Comment by jack99999** [comment] 2015-05-26 07:31
command-line-1: Cannot open load file: no such file or directory, omni-kill-20150525.937.el.txt

is that file supposed to exist already? fwiw, i do not have it on my system.

jack

**Comment by AdrieanKhisbe** [comment] 2015-05-26 08:09
That's the version you are using that I download from melpa: http://melpa.org/packages/omni-kill-20150525.937.el

:)

**Comment by jack99999** [comment] 2015-05-26 08:22
hmm. will try linux version at home, later. 

jack

**Comment by AdrieanKhisbe** [comment] 2015-05-26 08:22
Okey dokey :)

**Comment by ejmr** [comment] 2015-05-26 14:37
I get the same error.  I am using GNU Emacs 25.0.50.5 (x86_64-unknown-linux-gnu, GTK+ Version 3.12.2)

Here is the complete backtrace:

```
Debugger entered--Lisp error: (invalid-function omni-kill-generate-copy-command)
  omni-kill-generate-copy-command(symbol)
  omni-kill-generate-all-the-fun(symbol)
  #[(arg) "\301!\207" [arg omni-kill-generate-all-the-fun] 2](symbol)
  mapc(#[(arg) "\301!\207" [arg omni-kill-generate-all-the-fun] 2] (symbol list sexp defun filename url email word sentence whitespace line number page))
  omni-kill-get-all-the-things()
  byte-code("\300 \210\301\302!\207" [omni-kill-get-all-the-things provide omni-kill] 2)
  require(omni-kill)
  eval((require (quote omni-kill)) nil)
  elisp--eval-last-sexp(nil)
  #[257 "\204
```

**Comment by AdrieanKhisbe** [comment] 2015-05-26 15:22
Did you try to customize:  `omni-kill-naming-scheme`?

seems to me it might coming from there: https://github.com/AdrieanKhisbe/omni-kill.el/blob/master/omni-kill.el#L55-L59, with an extra () around the lambda.

**Comment by ejmr** [comment] 2015-05-26 15:24
> Did you try to customize: `omni-kill-naming-scheme`?

I did not.  Should I?  And if so what would you suggest?

**Comment by AdrieanKhisbe** [comment] 2015-05-26 15:26
I was saying bullshit. this is unrelated, but still need to be fix.

**Comment by AdrieanKhisbe** [comment] 2015-05-26 15:31
I think I spot it: 
cf http://stackoverflow.com/questions/15880783/emacs-complaining-with-invalid-function + 
https://github.com/AdrieanKhisbe/omni-kill.el/blob/master/omni-kill.el#L173-L176 

Missing `progn` to regroup message and nil.

Could you try to edit the file to see if it fix your issue?
(so that we don't have to wait melpa relase to know if working :))

```
  (if thing
         (,(intern (format "omni-kill-%s-thing-at-point" (eval action) )) thing)
       (progn
         (message "No thing is associated at letter %s  (for memory refresh, run `omni-help')" char)
       nil)))))
```

**Comment by ejmr** [comment] 2015-05-26 15:47
Based on your suggestion I changed the macro like so:

```
(defmacro omni-kill-generate-dispatch-command (action)
  "Generate a dispath command for the given ACTION."
 `(defun ,(intern (format "omni-%s" (eval action))) (char)
       ,(format "%s the thing associated with the given CHAR.
Association are stored in the `omni-kill-thing-to-letter-alist' variable" (capitalize (eval action))) ;§todo: doc
       (interactive "cPick a thing:");§later: recap list
       (let ((thing (cdr-safe (assoc char omni-kill-thing-to-letter-alist))))
         (if thing
             (,(intern (format "omni-kill-%s-thing-at-point" (eval action) )) thing)
           (progn
             (message "No thing is associated at letter %s  (for memory refresh, run `omni-help')" char))
             nil))))
```

And after that it works :)

Thank you for the help!

**Comment by AdrieanKhisbe** [comment] 2015-05-26 15:51
Your welcome. I thanks you for the test.
I commit and tag as patch release.

**Comment by AdrieanKhisbe** [comment] 2015-05-26 15:56
_voila :)_

@jack99999 confirm me that it's working when reinstalling/updating on your computer! :)

**Comment by jack99999** [comment] 2015-05-26 19:50
hi
i see you've been busy. 

at home, on linux, i saw the same problem. then i updated...

i have now upgraded to  Version: 20150526.852, and unfortunately still see the same error:
omni-kill-generate-all-the-fun: Invalid function: omni-kill-generate-copy-command

i will try on the original Windows machine in the morning.

jack

**Comment by AdrieanKhisbe** [comment] 2015-05-26 20:41
That's stange. but maybe the edit I made rebroked it.

@ejmr I you update to latest, can you reproduce the bug, or it's still working?

**Comment by ejmr** [comment] 2015-05-26 20:54
@AdrieanKhisbe I upgraded through the package manager and it still works for me.  It generates an error on compilation (line 151, unknown symbol `thing`) but after closing and restarting Emacs omni-kill still works for me.

**Comment by jack99999** [comment] 2015-05-26 20:58
i have just upgraded again, now picked up Version: 20150526.1240

and this loads without error :)

super!

jack

**Comment by AdrieanKhisbe** [comment] 2015-05-27 05:43
@jack99999 Cool, then I close the issue :)

@ejmr, yep I spot the compil error at `omni-kill-generate-all-the-fun (thing)`, which is strange. But didn't have time yet to investigate

**Closed as completed by AdrieanKhisbe** 2015-05-27 05:43 UTC
Labels: bug

**Comment by ejmr** [comment] 2015-05-27 05:54
I spent about ten minutes looking at the compilation error and didn't see anything obviously wrong that would be causing it.

**Comment by AdrieanKhisbe** [comment] 2015-05-27 05:58
_elisp mysteries_ ^^

**Comment by jack99999** [comment] 2015-05-27 06:38
i tried on my Windows machine.... still fails.

i discovered that if i delete omni-kill.elc then i can load omni-kill without error. i have no idea why this could be!

jack

**Comment by AdrieanKhisbe** [comment] 2015-05-27 06:45
You might have an older version that takes precedence on your windows

**Comment by jack99999** [comment] 2015-05-27 06:50
an older version of what. if you mean the .elc, then no. i deleted the package and reinstalled a couple of times. i have no other omni-kill files anywhere on the system.

**Comment by AdrieanKhisbe** [comment] 2015-05-27 07:00
then I don't have any idea why you can still load without error :/

**Comment by jack99999** [comment] 2015-05-27 07:05
surprisingly, neither have i :)

but it's working fine... i don't need a fix... and this machine has only another month to live, so i suggest we just ignore.

thanks

jack

**Comment by jack99999** [comment] 2015-05-27 14:38
fwiw, Version: 20150526.2349 is loading with no problems at all on Windows.

**Comment by AdrieanKhisbe** [comment] 2015-05-27 15:04
farpait :)
(perfect)
